#!/bin/sh

# build — Build El Cid

# El Cid (https://github.com/melusina-org/cid)
# This file is part of El Cid.
#
# Copyright © 2015–2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${developmentsystem:="org.melusina.cid/development"}

build_sbcl()
{
    sbcl --noinform --disable-debugger "$@"
}

build_main()
{
    build_sbcl --eval "
(unless (ql:where-is-system \"${developmentsystem}\")
 (push #p\"./\" ql:*local-project-directories*)
 (ql:register-local-projects))"\
		 --eval "(ql:quickload \"${developmentsystem}\" :silent t)"\
		 --eval "(${developmentsystem}:build)"\
		 --eval '(uiop:quit 0)'
}

build_main "$@"

# End of file `build'
