#!/bin/sh

# clean — Perform the clean step of lifecycle

# El Cid (https://github.com/melusina-org/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${subrdir:=${TOPLEVELDIR}/subr}

. "${subrdir}/stdlib.sh"
. "${subrdir}/config.sh"

clean_objdir()
(
    : "${OBJDIR:?}"

    if [ -d "${OBJDIR}" ]; then
	confirm 'clean: %s: Confirm object directory deletion?' "${OBJDIR}"
	rm -rf "${OBJDIR}"
    fi

    rmdir "${OBJDIR%/*}" 1>/dev/null 2>/dev/null
    return 0
)

clean_docker_containers()
(
    _query()
    {
	docker ps --all --format '{{ .ID }}|{{ .State }}|{{ .Status }}|{{ .Image }}|{{ .Command }}'
    }

    _select()
    {
	awk -F '|' '$2 == "exited"'
    }

    _delete()
    {
	local id _
	while IFS='|' read id _; do
	    docker rm "${id}"
	done
    }

    _query | _select | _delete
)

clean_docker_images()
(
    _query()
    {
	docker image ls --format '{{ .ID }}|{{ .Repository }}|{{ .Tag }}'
    }

    _select()
    {
	awk -F '|' -v OFS='|' '$2 == "<none>" || $3 == "<none>"'
    }

    _delete()
    {
	local id repository tag
	while IFS='|' read id repository tag; do
	    docker image rm "${id}"
	done
    }

    _query | _select | _delete
)

main()
{
    clean_objdir
    clean_docker_containers
    clean_docker_images
}

main "$@"

# End of file `clean'
