#!/bin/sh

# lint — Linter for El Cid

# El Cid (https://github.com/melusina-org/cid)
# This file is part of El Cid.
#
# Copyright © 2015–2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}

lint_sbcl()
{
    sbcl --noinform --disable-debugger "$@"
}

lint_main()
{
    lint_sbcl --eval '(ql:quickload "org.melusina.cid/development")'\
	      --eval '(org.melusina.cid/development:lint)'
}

lint_main "$@"

# End of file `lint'
