#!/bin/sh

# lint — Linter for El Cid

# El Cid (https://github.com/melusina-org/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}

lint_sbcl()
{
    sbcl --noinform "$@"
}

lint_main()
{
    lint_sbcl --load "${TOPLEVELDIR}/libexec/lisp/setup.lisp"\
	      --eval '(progn
(setf atelier:*linter-interactive-p* nil)
(atelier:lint
  #p"admin"
  #p"development"
  #p"environment"
  #p"libexec/lisp/setup.lisp"
  #p"libexec/setup"
  #p"operation"
  #p"script"
  #p"service"
  #p"src"
  #p"subr"
  #p"test"
  #p"testsuite"
  #p"tool"
)
)'
}

lint_main "$@"

# End of file `lint'
