#!/bin/sh

# makedoc — Make documentation

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This software is governed by the CeCILL-B license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL-B
# license as circulated by CEA, CNRS and INRIA at the following URL
# "https://cecill.info/licences/Licence_CeCILL-B_V1-en.txt"

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${subrdir:=${TOPLEVELDIR}/subr}
: ${makedocdir:=${TOPLEVELDIR}/obj/makedoc}
: ${makedocsystem:="org.melusina.cid"}

. "${subrdir}/stdlib.sh"

makedoc_sbcl()
{
    sbcl --noinform --disable-debugger "$@"
}

makedoc_runpatches()
{
    for patch in "${TOPLEVELDIR}"/doc/patch/*.sed; do
	include="${patch}"
	include="obj/makedoc/include/${include##*/patch/}"
	include="${include%.sed}.texinfo"
	if [ -f "${patch}" ]; then
	    sed_inplace -f "${patch}" "${include}"
	fi
    done
}

makedoc_extract()
{
    makedoc_sbcl \
	--eval "(ql:quickload :${makedocsystem})"\
	--eval '(with-compilation-unit () (load "libexec/lisp/docstrings.lisp"))' \
	--eval "(sb-texinfo:generate-includes \
	         \"obj/makedoc/include/\" (list :${makedocsystem}) \
		 :base-package :${makedocsystem})" \
	--eval '(quit)'
}

makedoc_info()
(
    cd "${TOPLEVELDIR}/obj/makedoc"
    makeinfo "${TOPLEVELDIR}/doc/${makedocsystem}.texinfo"
)

makedoc_pdf()
(
    cd "${TOPLEVELDIR}/obj/makedoc"
    texi2pdf "${TOPLEVELDIR}/doc/${makedocsystem}.texinfo"
)

makedoc_html()
(
    cd "${TOPLEVELDIR}/obj/makedoc"
    makeinfo --html --no-split "${TOPLEVELDIR}/doc/${makedocsystem}.texinfo"
)

makedoc_main()
{
    if [ ! -f "${TOPLEVELDIR}/doc/${makedocsystem}.texinfo" ]; then
	1>&2 printf 'Info: makedoc: There is no documentation master file.\n'
    fi
    if [ ! -f "${TOPLEVELDIR}/libexec/lisp/docstrings.lisp" ]; then
	1>&2 printf 'Info: makedoc: Cannot find docstrings lisp utility script.\n'
    fi
    set -e
    makedoc_extract
    makedoc_runpatches
    makedoc_info
    makedoc_html
    makedoc_pdf
}

makedoc_main "$@"

# End of file `makedoc'
