#!/bin/sh

# run — Perform the run step of lifecycle

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${subrdir:=${TOPLEVELDIR}/subr}

. "${subrdir}/stdlib.sh"
. "${subrdir}/config.sh"

main()
{
    : ${OBJDIR:?}
    local lisp_os lisp_image

    lisp_os=$(uname)
    lisp_image="${OBJDIR}/lisp/${lisp_os}/org.melusina.cid"

    if [ -x "${lisp_image}" ]; then
	"${lisp_image}" "$@"
    else
	failwith '%s: Lisp image has not been built yet.' "${lisp_image}"
    fi
}

main "$@"

### End of file `run'
# End of file `run'
