#!/bin/sh

# run — Perform the run step of lifecycle

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This software is governed by the CeCILL-B license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL-B
# license as circulated by CEA, CNRS and INRIA at the following URL
# "https://cecill.info/licences/Licence_CeCILL-B_V1-en.txt"

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${subrdir:=${TOPLEVELDIR}/subr}

. "${subrdir}/stdlib.sh"
. "${subrdir}/config.sh"

main()
{
    : ${OBJDIR:?}
    local lisp_os lisp_image

    lisp_os=$(uname)
    lisp_image="${OBJDIR}/lisp/${lisp_os}/org.melusina.cid"

    if [ -x "${lisp_image}" ]; then
	"${lisp_image}" "$@"
    else
	failwith '%s: Lisp image has not been built yet.' "${lisp_image}"
    fi
}

main "$@"

### End of file `run'
# End of file `run'
