#!/bin/sh

# setup — Perform the setup step of lifecycle

# El Cid (https://github.com/melusina-org/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${subrdir:=${TOPLEVELDIR}/subr}

. "${subrdir}/stdlib.sh"

setup_main()
{
    cat <<'EOF'
Welcome to the setup assistant for El Cid

Please ensure that the following software is installed on your
computer and that the correpsonding binaries can be found in the path
when you run other lifecycle steps:

 bmake
 docker
 git
 python3
 pip3
 sbcl

These packages can be installed with MacPorts:
  port install bmake docker git python39 py39-pip sbcl

Configure your git user.name and user.email for this repository.

Install quicklisp on your system and ensure that SBCL will load
quicklisp on startup.
EOF
}

setup_main

# End of file `setup'
