#!/bin/sh

# setup — Perform the setup step of lifecycle

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This software is governed by the CeCILL-B license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL-B
# license as circulated by CEA, CNRS and INRIA at the following URL
# "https://cecill.info/licences/Licence_CeCILL-B_V1-en.txt"

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${subrdir:=${TOPLEVELDIR}/subr}

. "${subrdir}/stdlib.sh"

setup_main()
{
    cat <<'EOF'
Welcome to the setup assistant for El Cid

Please ensure that the following software is installed on your
computer and that the correpsonding binaries can be found in the path
when you run other lifecycle steps:

 bmake
 docker
 git
 python3
 pip3
 sbcl

These packages can be installed with MacPorts:
  port install bmake docker git python39 py39-pip sbcl

Configure your git user.name and user.email for this repository.

Install quicklisp on your system and ensure that SBCL will load
quicklisp on startup.
EOF
}

setup_main

# End of file `setup'
