#!/bin/sh

# testsuite — Run test suite

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This software is governed by the CeCILL-B license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL-B
# license as circulated by CEA, CNRS and INRIA at the following URL
# "https://cecill.info/licences/Licence_CeCILL-B_V1-en.txt"

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${testsuitesystem:="org.melusina.cid/testsuite"}
: ${testsuiteclean:='no'}
: ${testsuitelisp:='sbcl'}

testsuite_lisp()
{
    case "${testsuitelisp}" in
	sbcl)
	    sbcl --noinform --disable-debugger "$@"
	    ;;
	ccl|ccl64)
	    ccl64 "$@"
	    ;;
    esac
}

testsuite_run()
{
    if [ $# -eq 0 ]; then
	set -- 'run-all-tests'
    fi
    testsuite_lisp\
	--eval "(ql:quickload \"${testsuitesystem}\" :silent t)"\
	--eval "(${testsuitesystem}:$1)"
}

testsuite_main()
{
    while getopts 'CL:' OPTARG; do
	case "${OPTION}" in
	    C)	testsuiteclean='yes';;
	    L)	testsuitelisp="${OPTARG}";;
	esac
    done

    shift $((OPTIND - 1))

    if [ "${testsuiteclean}" = 'yes' ]; then
	(cd "${TOPLEVELDIR}" && development/clean)
    fi
    
    testsuite_run "$@"
}

testsuite_main "$@"

# End of file `testsuite'
