#!/bin/sh

# entrypoint — Entrypoint for Console

# El Cid (https://github.com/melusina-org/cid)
# This file is part of El Cid.
#
# Copyright © 2015–2024 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

SBCL_HOME='/usr/lib/sbcl/'
export SBCL_HOME

start_console()
{
    exec su cid -c "/opt/cid/bin/console $@"
}

is_console_argument_p()
{
    case "${1:-NIL}" in
        -*)
	    return 0
            ;;
	listen|configure)
	    return 0
	    ;;
	*)
	    return 1
            ;;
    esac
}

if [ $# -eq 0 ]; then
    start_console
elif is_console_argument_p "$1"; then
    start_console "$@"
else
    exec "$@"
fi

# End of file `entrypoint'
