# Makefile — Shell Standard Library

# El Cid (https://github.com/melusina-org/cid)
# This file is part of El Cid.
#
# Copyright © 2015–2024 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

PACKAGE=		subr

LIBRARY=		stdlib.sh
LIBRARY+=		autoconf.sh
LIBRARY+=		config.sh
LIBRARY+=		role.sh

LIBRARY+=		gitserver.sh
LIBRARY+=		jenkins.sh
LIBRARY+=		trac.sh

.include "shell.lib.mk"

# End of file `Makefile'
