#!/bin/sh

# entrypoint — Entrypoint for the gitserver

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

set -e

run_sshd()
{
    /usr/sbin/sshd -D
}

if [ $# -gt 0 ]; then
    exec "$@"
else
    run_sshd
fi

# End of file `entrypoint'
