#!/bin/sh

# testimage — Test Docker Image for Personalised Linux system

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

set -ex
test -x /usr/bin/vi
test -x /usr/bin/sbcl
test -x /usr/bin/bsdtar
test -f /usr/local/share/bsdowl/bps.uses.mk 
id cid
id go
id git

# End of file `testimage'
