#!/bin/sh

# testimage — Test Docker Image for Personalised Linux system

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This software is governed by the CeCILL-B license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL-B
# license as circulated by CEA, CNRS and INRIA at the following URL
# "https://cecill.info/licences/Licence_CeCILL-B_V1-en.txt"

set -ex
test -x /usr/bin/vi
test -x /usr/bin/sbcl
test -x /usr/bin/bsdtar
test -f /usr/local/share/bsdowl/bps.uses.mk 
id cid
id go
id git

# End of file `testimage'
