\input texinfo   @c -*-texinfo-*-
@setfilename org.melusina.cid.info
@settitle El Cid Manual

@c for install-info
@dircategory Software development
@direntry
* org.melusina.cid: Count of Vivar and Prince of Continuous Integration and Deployment Systems
@end direntry

@copying
El Cid software and associated documentation is distributed
under the terms of the MIT License.

@quotation
Copyright © 2015–2023 Michaël Le Barbier
All rights reserved.

This file must be used under the terms of the MIT License.
This source file is licensed as described in the file LICENSE, which
you should have received as part of this distribution. The terms
are also available at https://opensource.org/licenses/MIT
@end quotation

@end copying
@titlepage

@title El Cid Manual
@subtitle draft version

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

@end titlepage

@contents

@c We use @andkey, etc to escape & from TeX in lambda lists --
@c so we need to define them for info as well.
@macro andallowotherkeys
&allow-other-keys@tie{}
@end macro
@macro andoptional
&optional@tie{}
@end macro
@macro andrest
&rest@tie{}
@end macro
@macro andkey
&key@tie{}
@end macro
@macro andbody
&body@tie{}
@end macro

@ifnottex

@node Top, , ,
@comment  node-name,  next,  previous,  up
@top El Cid

@insertcopying

@menu
* Introduction::
* Tenant::
* Project::
* Steward::
* Resource::
* Phony::
* Local Filesystem Subtree::
* Docker Engine::
@end menu

@end ifnottex

@node Introduction, Tenant, Top, Top
@include introduction.texinfo

@node Tenant, Project, Introduction, Top
@include tenant.texinfo

@node Project, Steward, Tenant, Top
@include project.texinfo

@node Steward, Resource, Project, Top
@include steward.texinfo

@node Resource, Phony, Steward, Top
@include resource.texinfo

@chapter Stewards and Resources

@node Phony, Local Filesystem Subtree, Top
@include phony.texinfo

@node Local Filesystem Subtree, Docker Engine, Top
@include local-filesystem-subtree.texinfo

@node Docker Engine, , Top
@include docker-engine.texinfo

@bye
