\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename org.melusina.cid.info
@settitle El Cid Manual
@c %**end of header

@c for install-info
@dircategory Software development
@direntry
* cid:           Continuous Integration and Delivery
@end direntry

@copying
El Cid software and associated documentation is distributed
under the terms of the MIT License.

@quotation
Copyright © 2017–2022 Michaël Le Barbier
All rights reserved.

This file must be used under the terms of the MIT License.
This source file is licensed as described in the file LICENSE, which
you should have received as part of this distribution. The terms
are also available at https://opensource.org/licenses/MIT
@end quotation

@end copying
@titlepage

@title El Cid Manual
@subtitle draft version

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

@end titlepage

@contents

@c We use @andkey, etc to escape & from TeX in lambda lists --
@c so we need to define them for info as well.
@macro andallowotherkeys
&allow-other-keys
@end macro
@macro andoptional
&optional
@end macro
@macro andrest
&rest
@end macro
@macro andkey
&key
@end macro
@macro andbody
&body
@end macro

@ifnottex

@include include/ifnottex.texinfo

@node Top, , ,
@comment  node-name,  next,  previous,  up
@top Cid

@insertcopying

@menu
* Introduction::
* Infrastructure::
* Null Provider::
* Docker Engine::
@end menu

@end ifnottex

@node Introduction, Infrastructure, Top, Top
@chapter Introduction

The @b{El Cid} project aims at providing a complete continuous
integration and delivery system that is easy to incrementally
improve, to share with team mates and collaborators, and that can be
deployed trivially either locally, on bare metal or in the cloud.

It is based on Debian, Ubuntu, Haproxy, GoCD, Gitea, trac.

@node Infrastructure, Null Provider, Introduction, Top
@chapter The Infrastructure Dictionary

@include include/class-cid-provider.texinfo
@include include/fun-cid-configure-provider.texinfo
@include include/class-cid-resource.texinfo
@include include/condition-cid-resource-error.texinfo
@include include/condition-cid-resource-confirmation.texinfo
@include include/fun-cid-resource-error.texinfo
@include include/fun-cid-resource-confirmation.texinfo
@include include/fun-cid-create-resource.texinfo
@include include/fun-cid-actually-create-resource.texinfo
@include include/fun-cid-read-resource.texinfo
@include include/fun-cid-actually-read-resource.texinfo
@include include/fun-cid-update-resource.texinfo
@include include/fun-cid-actually-update-resource.texinfo
@include include/fun-cid-delete-resource.texinfo
@include include/fun-cid-actually-delete-resource.texinfo
@include include/fun-cid-import-resource.texinfo
@include include/fun-cid-actually-import-resource.texinfo

@include include/class-cid-computing-resource.texinfo
@include include/fun-cid-start-resource.texinfo
@include include/fun-cid-actually-start-resource.texinfo
@include include/fun-cid-stop-resource.texinfo
@include include/fun-cid-actually-stop-resource.texinfo

@include include/class-cid-stateful-resource.texinfo
@include include/fun-cid-dump-resource.texinfo
@include include/fun-cid-actually-dump-resource.texinfo
@include include/fun-cid-restore-resource.texinfo
@include include/fun-cid-actually-restore-resource.texinfo

@node Null Provider, Docker Engine, Infrastructure, Top
@chapter Null Provider

@include include/class-cid-null-provider.texinfo
@include include/fun-cid-make-null-provider.texinfo

@node Docker Engine, , Null Provider, Top
@chapter Docker Engine

@include include/class-cid-docker-engine.texinfo
@include include/fun-cid-make-docker-engine.texinfo

@bye
