#!/bin/sh

# docker_gc — Garbage Collect Docker Resources

# El Cid (https://github.com/melusina-org/cid)
# This file is part of El Cid.
#
# Copyright © 2015–2024 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}

gc_package='cid'

gc_images()
{
    docker images --filter 'dangling=true' --quiet\
        | xargs docker rmi
}


gc_container()
{
    {
        docker ps --filter 'status=exited' --quiet
        docker ps --filter 'status=dead' --quiet
    } | xargs docker rm
}


gc_main()
{
    gc_container
    gc_images
}

gc_main "$@"

# End of file `docker_gc'
