#!/bin/sh

# bsdowl — Setup BSD Owl

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

bsdowl_dependencies()
{
    env DEBIAN_FRONTEND=noninteractive apt-get install -y\
	autoconf\
	bmake\
	libarchive-tools\
	curl
}

bsdowl_build()
{
    install -d -o cid -g cid -m 700 /usr/local/src
    su -l cid -c '
 set -e	  
 cd /usr/local/src
 curl -L https://github.com/foretspaisibles/bsdowl/archive/master.zip | bsdtar xf -
 cd bsdowl-master
 autoconf
 ./configure --prefix=/usr/local --with-credentials=sudo
 bmake all
'
}

bsdowl_install()
(
    cd /usr/local/src/bsdowl-master
    bmake install
)

bsdowl_clean()
{
    rm -Rf /usr/local/src/bsdowl-master
}

bsdowl_main()
{
    bsdowl_dependencies
    bsdowl_build
    bsdowl_install
    bsdowl_clean
}

bsdowl_main "$@"

# End of file `bsdowl'
