#!/bin/sh

# docker — Setup docker

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This software is governed by the CeCILL-B license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL-B
# license as circulated by CEA, CNRS and INRIA at the following URL
# "https://cecill.info/licences/Licence_CeCILL-B_V1-en.txt"

#
# Docker group
#
#  In boot2docker, the docker socket is owned by group docker (100)
#  but in Debian, the group 100 is users. We therefore remove the
#  group users and create a group docker with the correct gid.

groupdel users
groupadd -g 100 docker

env DEBIAN_FRONTEND=noninteractive apt-get install -y\
 docker-ce

# End of file `docker'
