#!/bin/sh

### testimage -- Test Docker image

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This software is governed by the CeCILL-B license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL-B
# license as circulated by CEA, CNRS and INRIA at the following URL
# "https://cecill.info/licences/Licence_CeCILL-B_V1-en.txt"

: ${PACKAGE:=cid}
: ${testimage_package:=${PACKAGE}}
: ${testimage_testsuite:=/opt/${testimage_package}/libexec/testimage}
: ${testimage_configfile:=/opt/${testimage_package}/etc/setup/users.conf}

eprintf()
{
    1>&2 printf "$@"
}

testimage_main()
{
    local overall testcase
    overall='SUCCESS'
    for testcase in ${testimage_testsuite}/*; do
	printf 'testimage: Info: %s\n' "${testcase##*/}"
	if ! ${testcase}; then
	    overall='FAILURE'
	fi
    done

    case "${overall}" in
	SUCCESS)
	    exit 0
	    ;;
	FAILURE)
	    eprintf 'testimage: Error: There were some failures.\n'
	    exit 1
	    ;;
    esac
}

testimage_main "$@"

### End of file `testimage'
