#!/bin/sh

# entrypoint — Entrypoint for Jenkins

# El Cid (https://github.com/melusina-org/cid)
# This file is part of El Cid.
#
# Copyright © 2015–2024 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

set -e

chown root:docker /var/run/docker.sock
chown jenkins:jenkins /var/lib/jenkins

if [ "$#" -le 0 ]; then
    #set -- sudo -u jenkins java -jar /usr/share/jenkins/jenkins.war
    set -- su - jenkins -l -s /bin/sh -c '
set -a
JENKINS_HOME=/var/lib/jenkins
LC_ALL="en_US.UTF_8"
LANG="en_US.UTF-8"
set +a
java -jar /usr/share/jenkins/jenkins.war
'
fi

exec "$@"

# End of file `entrypoint'
