#!/bin/sh

# entrypoint — Entrypoint for trac

# El Cid (https://github.com/melusina-conseil/cid)
# This file is part of El Cid.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

run_apache()
{
    exec /usr/sbin/apache2ctl -DFOREGROUND
}

main()
{
    if [ $# -gt 0 ]; then
	exec "$@"
    else
	run_apache
    fi
}

main "$@"

# End of file `entrypoint'
