# cid.yml — Docker Compose File for El Cid Laboratory

# El Cid (https://github.com/melusina-org/cid)
# This file is part of El Cid.
#
# Copyright © 2015–2024 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at
# https://opensource.org/licenses/MIT

# Variables:
#
# cid_image_tag (latest):
#  The image tag to use when creating the project services.
#
# cid_project (local):
#  The project name to use when forming volume names.
#
# cid_http_port (80):
#  The port to bind the HTTP listener to.
#
# cid_https_port (443):
#  The port to bind the HTTPS listener to.
#
# cid_hostname (localhost):
#  The configured hostname for the system.
#
# cid_keycloak_password (Administrator):
#  The administrator password for Keycloak.

services:
 reverseproxy:
  restart: unless-stopped
  image: cid/reverseproxy:${cid_image_tag:-latest}
  networks:
   - service
   - frontend
  ports:
   - "127.0.0.1:${cid_http_port:-80}:80"
   - "127.0.0.1:${cid_https_port:-443}:443"
  volumes:
   - cid-ssl:/etc/ssl/private

 keycloak:
  image: quay.io/keycloak/keycloak:25.0.4
  environment:
   KEYCLOAK_ADMIN: 'Administrator'
   KEYCLOAK_ADMIN_PASSWORD: ${cid_keycloak_password:-Administrator}
   KC_HTTP_RELATIVE_PATH: '/authorization'
   KC_PROXY_HEADERS: 'xforwarded'
   KC_HTTP_ENABLED: 'true'
   KC_METRICS_ENABLED: 'true'
   KC_HEALTH_ENABLED: 'true'
  command: start-dev
  networks:
   - service

 gitserver:
  image: cid/gitserver:${cid_image_tag:-latest}
  #command: /usr/sbin/sshd -D -d
  volumes:
   - cid-git:/var/git
   - cid-trac:/var/trac
  networks:
   - frontend
  ports:
   - "127.0.0.1:${cid_ssh_port:-2022}:22"

 trac:
  image: cid/trac:${cid_image_tag:-latest}
  volumes:
   - cid-trac:/var/trac
   - cid-git:/var/git
   - cid-www:/var/www
  networks:
   - service

networks:
 frontend:
 service:

volumes:
  cid-ssl:
    name: cid-${cid_project:-local}-ssl
    external: true
  cid-trac:
    name: cid-${cid_project:-local}-trac
    external: true
  cid-git:
    name: cid-${cid_project:-local}-git
    external: true
  cid-www:
    name: cid-${cid_project:-local}-www
    external: true

# End of file `cid.yml'
