# cid.yml -- Docker Compose File for El Cid Laboratory

# El Cid (https://github.com/melusina-org/cid)
# This file is part of El Cid.
#
# Copyright © 2015–2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at
# https://opensource.org/licenses/MIT

version: '3'

services:
 reverseproxy:
  restart: unless-stopped
  image: cid/reverseproxy
  networks:
   - service
   - frontend
  ports:
   - "80:80"
   - "443:443"

 gitserver:
  image: cid/gitserver
  #command: /usr/sbin/sshd -D -d
  volumes:
   - cid-git:/var/git
   - cid-trac:/var/trac
  networks:
   - frontend
  ports:
   - "2022:22"

 trac:
  image: cid/trac
  volumes:
   - cid-trac:/var/trac
   - cid-git:/var/git
   - cid-www:/var/www
  networks:
   - service

networks:
 frontend:
 service:

volumes:
  cid-trac:
    external:
      name: cid-${cid_project}-trac
  cid-git:
    external:
      name: cid-${cid_project}-git
  cid-www:
    external:
      name: cid-${cid_project}-www

# End of file `cid.yml'
