version: '3.1'

services:
  reverseproxy:
    image: 'cid/reverseproxy'
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - bundle.pem
    depends_on:
      - gocdserver
      - trac
  trac:
    image: 'cid/trac'
    volumes:
      - 'gitserver_data:/var/git'
      - 'trac_data:/var/trac'
  gitserver:
    image: 'cid/gitserver'
    volumes:
      - 'gitserver_data:/var/git'
      - 'trac_data:/var/trac'
    ports:
      - "2022:22"
  gocdserver:
    image: 'cid/gocdserver'
    volumes:
      - 'gocdserver_home:/home/go'
      - 'gocdserver_data:/godata'
      - "${CID_TENANT_DIR}/ssh/:/home/go/.ssh/"
  docker:
    image: 'docker:stable-dind'
    environment:
      DOCKER_TLS_CERTDIR: ""
    privileged: true
  gocdagent:
    image: "cid/gocdagent"
    depends_on:
      - gocdserver
    environment:
      GO_AGENT_SYSTEM_PROPERTIES: '-Xms1024m -Xmx1024m'
      GO_SERVER_URL: https://gocdserver:8154/go
      DOCKER_HOST: tcp://docker:2375
    volumes:
      - 'gocdagent_home:/home/go'
      - 'gocdagent_data:/godata'
      - "${CID_TENANT_DIR}/ssh/:/home/go/.ssh/"
volumes:
  gocdserver_home:
    name: "${CID_TENANT_NAME}.gocdserver_home"
  gocdserver_data:
    name: "${CID_TENANT_NAME}.gocdserver_data"
  gocdagent_home:
    name: "${CID_TENANT_NAME}.gocdagent_home"
  gocdagent_data:
    name: "${CID_TENANT_NAME}.gocdagent_data"
  trac_data:
    name: "${CID_TENANT_NAME}.trac_data"
  gitserver_data:
    name: "${CID_TENANT_NAME}.gitserver_data"
secrets:
  bundle.pem:
    file: "${CID_TENANT_DIR}/ssl/${CID_TENANT_NAME}.bundle.pem"
